version = 0.1
[default.deploy.parameters]
stack_name = "bizeng-latam-wamg-stk"
resolve_s3 = true
s3_prefix = "bizeng-latam-wamg-stk"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
